project_id = "rotuystkhggxbcvtarij"

[functions.generate-adaptation]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.extract-questions]
verify_jwt = false

[functions.adapt-activity]
verify_jwt = false
